"""
Django settings for ProjectAutomation project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import django_heroku
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    #'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AutomationApp',
    'whitenoise.runserver_nostatic',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',

]

ROOT_URLCONF = 'ProjectAutomation.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',


            ],
        },
    },
]



WSGI_APPLICATION = 'ProjectAutomation.wsgi.application'
TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
)

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
import dj_database_url
Identifierdb = "Heroku"
#Rail or Heroku
if Identifierdb == "Rail":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'railway',
            'USER': 'postgres',
            'PASSWORD': 'MyRKbNRuLN9bBsnnETFN',
            'HOST': 'containers-us-west-41.railway.app',
            'PORT': '6661',
        }
    }
    db_from_env = dj_database_url.config(conn_max_age=600)
    DATABASES['default'] = dj_database_url.parse('postgresql://postgres:MyRKbNRuLN9bBsnnETFN@containers-us-west-41.railway.app:6661/railway', conn_max_age=600)
    #DATABASES['default'] = dj_database_url.parse('postgres://postgres:0918382947kJ@localhost:5432/firstapp', conn_max_age=600)

    DATABASES['default'].update(db_from_env)

elif Identifierdb == "Heroku":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'd3sthqr8n69tio',
            'USER': 'skcxlyichpsdoh',
            'PASSWORD': 'ad2bfe7b2000a03803ef1b8dd48b6c903afbfd2ec4959056b57c9e2f1021da06',
            'HOST': 'ec2-52-203-99-122.compute-1.amazonaws.com',
            'PORT': '5432',
        }
    }
    db_from_env = dj_database_url.config(conn_max_age=600)
    #DATABASES['default'] = dj_database_url.parse('postgresql://postgres:MyRKbNRuLN9bBsnnETFN@containers-us-west-41.railway.app:6661/railway', conn_max_age=600)
    DATABASES['default'] = dj_database_url.parse('postgres://skcxlyichpsdoh:ad2bfe7b2000a03803ef1b8dd48b6c903afbfd2ec4959056b57c9e2f1021da06@ec2-52-203-99-122.compute-1.amazonaws.com:5432/d3sthqr8n69tio', conn_max_age=600)

    DATABASES['default'].update(db_from_env)




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
    ]

STATIC_ROOT = os.path.join(BASE_DIR,'assets')


MEDIA_URL = '/media/'
MEDIAFILES_DIRS=[
    os.path.join(BASE_DIR,'media')
    ]

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
django_heroku.settings(locals())
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTHENTICATION_BACKEND = {
#needed to login with username in django admin, regardless of allauth
'django.contrib.auth.backends.ModelBackend',

# 'allauth' specific application methods, such as login by email
'allauth.account.auth_backends.AUTHENTICATION_BACKEND',

}

SITE_ID=2

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'
ACCOUNT_LOGOUT_REDIRECT_URL ='../../index/onlineorder/4' 
#ACCOUNT_ADAPTER = 'app.my_adapter.MyAccountAdapter'
#LOGIN_REDIRECT_URL = 'next'
#LOGIN_REDIRECT_URL = 'request.path_info'

SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'js_sdk',
        'SCOPE': ['public_profile, email'],
        'AUTH_PARAMS': {'auth_type': 'reauthorize'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'name',
            'email',
            'short_name',
            'first_name',
            'last_name',
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
}
