# Generated by Django 4.1.3 on 2022-11-07 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorychoices', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSizechoices', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sizechoices', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subcategorychoices', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default='')),
                ('Cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=7)),
                ('Qty', models.IntegerField(default='1')),
                ('Promo', models.CharField(default='', max_length=50)),
                ('Productimg', models.ImageField(blank=True, null=True, upload_to='Productimg')),
                ('Category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='AutomationApp.categories')),
                ('PSize', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='AutomationApp.psizes')),
                ('Size', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='AutomationApp.sizes')),
                ('Subcategory', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='AutomationApp.subcategories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
