# Generated by Django 4.1.3 on 2022-11-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0003_remove_user1_productimg_user1_pdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='PDescription',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
