# Generated by Django 4.1.3 on 2022-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0004_alter_user1_pdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='productname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
