# Generated by Django 4.1.3 on 2022-11-16 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutomationApp', '0005_alter_user1_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryCouponchoices', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='couponlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponname', models.CharField(default='', max_length=250)),
                ('code', models.CharField(default='', max_length=250)),
                ('url', models.CharField(default='', max_length=1000)),
                ('qr', models.CharField(default='', max_length=250)),
                ('pieces', models.IntegerField(blank=True, default='', null=True)),
                ('discountamount', models.IntegerField(blank=True, default='', null=True)),
                ('validfrom', models.DateTimeField(blank=True, default='', null=True)),
                ('validuntil', models.DateTimeField(blank=True, default='', null=True)),
                ('is_withMinimumAmount', models.BooleanField(blank=True, default=False, null=True)),
                ('is_consumed', models.BooleanField(blank=True, default=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('MinimumAmount', models.IntegerField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='AutomationApp.categoriescoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
