# Generated by Django 4.1.3 on 2022-11-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0006_categoriescoupon_couponlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponlist',
            name='is_withvalidity',
            field=models.CharField(default='', max_length=250),
        ),
    ]
