# Generated by Django 4.1.3 on 2022-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0007_couponlist_is_withvalidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponlist',
            name='validfrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponlist',
            name='validuntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
