# Generated by Django 4.1.3 on 2022-11-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0008_alter_couponlist_validfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponlist',
            name='is_withvalidity',
        ),
        migrations.RemoveField(
            model_name='couponlist',
            name='validfrom',
        ),
        migrations.RemoveField(
            model_name='couponlist',
            name='validuntil',
        ),
        migrations.AddField(
            model_name='sales',
            name='RequiredMinimumAmount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='codecoupon',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='discount',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='couponlist',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='couponlist',
            name='is_consumed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
