# Generated by Django 4.1.3 on 2022-11-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0010_remove_couponlist_qr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponlist',
            old_name='is_consumed',
            new_name='is_consumable',
        ),
        migrations.AddField(
            model_name='couponlist',
            name='numberredeem',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
