# Generated by Django 4.1.3 on 2022-11-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0012_alter_couponlist_numberredeem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponlist',
            name='numberredeem',
        ),
        migrations.AddField(
            model_name='couponlist',
            name='redeemlimit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
