# Generated by Django 4.1.3 on 2022-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0013_remove_couponlist_numberredeem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptorder',
            name='codecoupon',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='codecoupon',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rejectorder',
            name='codecoupon',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
