# Generated by Django 4.1.3 on 2022-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0014_acceptorder_codecoupon_customer_codecoupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptorder',
            name='Customername',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acceptorder',
            name='LandmarksnNotes',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='acceptorder',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Barangay',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customername',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LandmarksnNotes',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
