# Generated by Django 4.1.3 on 2022-12-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0016_alter_acceptorder_gsubtotal_alter_customer_gsubtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptorder',
            name='discount',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='rejectorder',
            name='discount',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='PDescription',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='Promo',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
