# Generated by Django 4.1.3 on 2022-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0017_acceptorder_discount_customer_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptorder',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='rejectorder',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=7, null=True),
        ),
    ]
