# Generated by Django 4.1.3 on 2022-12-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0018_alter_acceptorder_subtotal_alter_customer_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='Sales',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=7, null=True),
        ),
    ]
