# Generated by Django 4.1.3 on 2023-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0021_alter_messengerbag_fbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgedstockorder',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='punchedprod',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='punchedprodso',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='queue1',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='queue2',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='queue3',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='rejectorder',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='submitstockorder',
            name='productname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user1',
            name='productname',
            field=models.CharField(default='', max_length=250),
        ),
    ]
