# Generated by Django 4.1.3 on 2023-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0022_alter_acknowledgedstockorder_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptorder',
            name='LandmarksnNotes',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LandmarksnNotes',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rejectorder',
            name='LandmarksnNotes',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='CusName',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='LandmarksnNotes',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
