# Generated by Django 4.1.3 on 2023-02-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0024_employee_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprint',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
