# Generated by Django 4.1.3 on 2023-06-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0026_remove_timesheet_productimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, default='2', null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
