# Generated by Django 4.1.3 on 2023-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0027_buttoncolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttoncolor',
            name='cardcolor',
            field=models.CharField(default='#d4ad98', max_length=7),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='textcolor',
            field=models.CharField(default='#2c170c', max_length=7),
        ),
        migrations.AlterField(
            model_name='buttoncolor',
            name='color',
            field=models.CharField(default='#aa5c31', max_length=7),
        ),
    ]
