# Generated by Django 4.1.3 on 2023-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0029_buttoncolor_backgroundcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttoncolor',
            name='body',
            field=models.CharField(blank=True, default='sans-serif', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='brandname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='subtitle',
            field=models.CharField(blank=True, default='sans-serif', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='title',
            field=models.CharField(blank=True, default='Black Jack Script', max_length=50, null=True),
        ),
    ]
