# Generated by Django 4.1.3 on 2023-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0030_buttoncolor_body_buttoncolor_brandname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttoncolor',
            name='subtitle',
            field=models.CharField(blank=True, default='Black Jack Script', max_length=50, null=True),
        ),
    ]
