# Generated by Django 4.1.3 on 2023-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutomationApp', '0031_alter_buttoncolor_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttoncolor',
            name='body_bold',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='body_italic',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='body_underline',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='subtitle_bold',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='subtitle_italic',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='subtitle_underline',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='title_bold',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='title_italic',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buttoncolor',
            name='title_underline',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
